In [1]:
import pandas as pd

df = pd.read_csv(
    "./data/delivery_performance_cleaned.csv",
    parse_dates=["order_date", "expected_delivery_date", "actual_delivery_date"]
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2991 entries, 0 to 2990
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              2991 non-null   int64
 1   order_id                2991 non-null   object
 2   warehouse_id            2991 non-null   object
 3   order_date              2991 non-null   datetime64[ns]
 4   expected_delivery_date  2991 non-null   datetime64[ns]
 5   actual_delivery_date    2991 non-null   datetime64[ns]
 6   units                   2991 non-null   int64
dtypes: datetime64[ns](3), int64(2), object(2)
memory usage: 163.7+ KB

### **EDA and KPIs**

In [ ]:
# datset shape
df.shape

dims_count = {
    "Orders Count": df["order_id"].nunique(),
    "Warehouses Count": df["warehouse_id"].nunique()
}
dims_count

{'Orders Count': 2991, 'Warehouses Count': 5}

### **Orders Distribution by Warehouse**

In [2]:
# orders distribution by warehouse
orders_by_warehouse = (
    df
        .groupby("warehouse_id")
        .agg(
            orders_count = ("order_id", "nunique")
        )
        .sort_values("orders_count", ascending = False)
)
orders_by_warehouse["percentage"] = (orders_by_warehouse["orders_count"] * 100 / orders_by_warehouse["orders_count"].sum()).round(2)
orders_by_warehouse

              orders_count  percentage
warehouse_id
WH_E                  1055       35.27
WH_D                   734       24.54
WH_C                   582       19.46
WH_B                   359       12.00
WH_A                   261        8.73

In [3]:
# orders segmentation
df["delivery_status"] = (
    df["actual_delivery_date"] <= df["expected_delivery_date"]
).map(
    {
        True: "On-Time",
        False: "Late"
    }
)
df.head()

,Unnamed: 0,order_id,warehouse_id,order_date,expected_delivery_date,actual_delivery_date,units,delivery_status
0,0,ORD_00064,WH_C,2026-03-10,2026-03-12,2026-03-12,14,On-Time
1,1,ORD_02684,WH_C,2026-02-17,2026-02-20,2026-02-20,18,On-Time
2,2,ORD_00103,WH_C,2026-03-08,2026-03-11,2026-03-12,15,Late
3,3,ORD_02692,WH_D,2026-03-29,2026-04-02,2026-04-02,45,On-Time
4,4,ORD_00417,WH_C,2026-03-07,2026-03-11,2026-03-11,17,On-Time

### **delivery_status orders distribution**

In [4]:
orders_by_delivery_status = (
    df
        .groupby("delivery_status")
        .agg(
            orders_count = ("order_id", "nunique")
        )
)
orders_by_delivery_status

                 orders_count
delivery_status
Late                      848
On-Time                  2143